name: Deploy to PyPi
on:  
  release:     
    types: [created]  
jobs:  
  upload:  
    environment:
      name: release
      url: https://pypi.org/p/pdm-datareader
    permissions:
      contents: read
      id-token: write
    
    runs-on: ubuntu-latest
    steps:        
      - name: "Check out code"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      
      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:          
          python-version: 3.12      
      
      - name: "Install dependencies"            
        run: |
          python3 -m pip install --upgrade pip              
          python3 -m pip install poetry

      - name: "Build distributions"            
        run: |              
          poetry build
          
      - name: "Publish package distributions to PyPI"
        uses: pypa/gh-action-pypi-publish@release/v1
        