name: Test Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-deploy:
    environment:
      name: test_release
      url: https://test.pypi.org/p/pdm-datareader
    permissions:
      contents: read
      id-token: write
    
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]

    runs-on: ubuntu-latest  
    steps:
      - name: "Check out code"
        uses: actions/checkout@v3
      
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: actions/setup-python@v5
        with:          
          python-version: ${{ matrix.python-version }}
      
      - name: "Installs dependencies"            
        run: |
          python -m pip install --upgrade pip              
          python -m pip install poetry twine
      
      - name: "Build distribution"
        run: |
          poetry build
          twine check dist/*
          
      - name: "Publish package distributions to PyPI Test"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
